### ISSUE TITLE
"Generate test document" does not consider embosser limitations

### ISSUE THREAD

**Issue by joeha480** [brailleapps/dotify-studio#13]
When generating a test document, embosser limitations are not considered. For 
example, Braillo 400SR cannot produce more than 31 cells on an A4 paper, but 
when using this embosser and setting it for A4 sized paper, the software 
produces a test file that is 35 cells wide, which cannot be embossed on an A4 
paper with that embosser.

**Comment by joeha480** [comment]
Apparently, unprintable areas are not implemented on any embossers except MountbattenEmbosser. I was under the impression that this was implemented. Do you remember, @bertfrees?

**Comment by bertfrees** [comment]
Don't remember, but I just looked at the svn history, and it seems that it was implemented for several embossers:

- [IndexEmbosser](https://github.com/brailleapps/brailleutils/commit/aed460143d9bcabd60f1d4174cb3dfbcdb13f657)
- [EnablingTechnologiesEmbosser](https://github.com/brailleapps/brailleutils/commit/aed460143d9bcabd60f1d4174cb3dfbcdb13f657)
- [TigerEmbosser](https://github.com/brailleapps/brailleutils/commit/05fec738120319aa6d48fe11e7fce448c2c65f5d)
- [MountbattenEmbosser](https://github.com/brailleapps/brailleutils/commit/938af751ea90614de095545f94c8e4d2b99a73ff)
- [Interpoint55Embosser](https://github.com/brailleapps/brailleutils/commit/2a352e82526adac991fbc8c22d53b6612bdcef4b)
- [IndexV4Embosser](https://github.com/brailleapps/brailleutils/commit/59c40ba91283ed2f3211c29527e23785ec393fb3)

**Comment by bertfrees** [comment]
The printable area seems to be non-trivial at least for these two cases:
- [IndexEmbosser](https://github.com/brailleapps/brailleutils/blob/aed460143d9bcabd60f1d4174cb3dfbcdb13f657/braille/catalog/com_indexbraille/IndexEmbosser.java#L242)
- [MountbattenEmbosser](https://github.com/brailleapps/brailleutils/blob/938af751ea90614de095545f94c8e4d2b99a73ff/braille/catalog/pl_com_harpo/MountbattenEmbosser.java#L165)

**Comment by bertfrees** [comment]
I assume that Index is why I implemented this thing in the first place.

**Comment by joeha480** [comment]
Closing since this is in fact a problem with the embosser implementations.
