### ISSUE TITLE
Norwegian GUI translation

### ISSUE THREAD

**Issue by joeha480** [brailleapps/dotify-studio#39]
Add a Norwegian translation to the GUI.

**Comment by joeha480** [comment]
1. Make a copy of this file: https://github.com/brailleapps/dotify-studio/blob/master/src/application/l10n/messages.properties with the name 'messages_no.properties'
2. Translate
3. (optional, but highly recommended) verify the results by compiling and starting the application. If the OS-language is not set to Norwegian, start with `-Duser.country=NO -Duser.language=no`

**Comment by josteinaj** [comment]
@joeha480 https://github.com/brailleapps/dotify-studio/pull/40

**Comment by joeha480** [comment]
@josteinaj Nice! I forgot to mention: the encoding of these files must be ISO 8859-1, see https://docs.oracle.com/javase/8/docs/api/java/util/Properties.html

I fixed this and rebased on master, see 545dfd2ccbe97f56857786d6ca39d1c6af436c5a.

I will try to keep you updated as I add new entries to localize. Thanks!
